import pydantic
import typing_extensions


class V1AiVoiceGeneratorCreateBodyStyle(typing_extensions.TypedDict):
    """
    The content used to generate speech.
    """

    prompt: typing_extensions.Required[str]
    """
    Text used to generate speech. The character limit is 1000 characters.
    """

    voice_name: typing_extensions.Required[
        typing_extensions.Literal[
            "21 Savage",
            "50 Cent",
            "A.R. Rahman",
            "Aamir Khan",
            "Abraham Lincoln",
            "Adam Driver",
            "Adam Sandler",
            "Adele",
            "Ajay Devgn",
            "Akshay Kumar",
            "Al Pacino",
            "Alain Delon",
            "Alan Alda",
            "Alan Cumming",
            "Alan Rickman",
            "Albert Einstein",
            "Alex Trebek",
            "Alexandria Ocasio-Cortez",
            "Alexz Johnson",
            "Ali Wong",
            "All Might",
            "Amitabh Bachchan",
            "Amy Poehler",
            "Amy Winehouse",
            "Ana Gasteyer",
            "Ana de Armas",
            "Anderson Cooper",
            "Andrew Huberman",
            "Andrew Rannells",
            "Ang Lee",
            "Angelina Jolie",
            "Anne Hathaway",
            "Ansel Elgort",
            "Anthony Anderson",
            "Anthony Bourdain",
            "Anthony Mackie",
            "Antonio Banderas",
            "Arden Cho",
            "Ariana Grande",
            "Armie Hammer",
            "Arnold Schwarzenegger",
            "Arthur Morgan",
            "Asa Butterfield",
            "Austin Butler",
            "Awkwafina",
            "B.J. Novak",
            "BTS Jungkook",
            "Bad Bunny",
            "Barack Obama",
            "Barbara Eden",
            "Barry White",
            "Bart Simpson",
            "Batman (Animated)",
            "Bear Grylls",
            "Ben McKenzie",
            "Ben Shapiro",
            "Ben Stiller",
            "Ben Whishaw",
            "Bender (Futurama)",
            "Benedict Cumberbatch",
            "Bernie Sanders",
            "Betty White",
            "Bill Gates",
            "Bill Nighy",
            "Bill Nye",
            "Bill Pullman",
            "Billie Eilish",
            "Billie Joe Armstrong",
            "Bingbing Li",
            "Blake Shelton",
            "Bo Burnham",
            "Bob Dylan",
            "Bob Marley",
            "Bob Odenkirk",
            "Bob Ross",
            "Bonnie Wright",
            "Booboo Stewart",
            "Bowser",
            "Brad Paisley",
            "Brad Pitt",
            "Bradley Steven Perry",
            "Brendan Gleeson",
            "Brian Cox",
            "Bruno Ganz",
            "Bruno Mars",
            "Bryan Cranston",
            "Bugs Bunny",
            "Burt Reynolds",
            "Buzz Lightyear",
            "Caitriona Balfe",
            "Caity Lotz",
            "Cameron Boyce",
            "Candice Accola",
            "Captain Jack Sparrow",
            "Cardi B",
            "Carrie Fisher",
            "Carrie Underwood",
            "Casey Affleck",
            "Cate Blanchett",
            "Caterina Scorsone",
            "Cedric the Entertainer",
            "Chace Crawford",
            "Chadwick Boseman",
            "Chappell Roan",
            "Charles Barkley",
            "Charles Dance",
            "Charlie Chaplin",
            "Charlie Day",
            "Chiwetel Ejiofor",
            "Chris Hemsworth",
            "Chris Martin",
            "Chris Pine",
            "Chris Rock",
            "Christina Hendricks",
            "Christina Ricci",
            "Christopher Mintz-Plasse",
            "Christopher Walken",
            "Cillian Murphy",
            "Conan O'Brien",
            "Conor McGregor",
            "Corpse Husband",
            "Cristiano Ronaldo",
            "Cyndi Lauper",
            "Dakota Fanning",
            "Damian Lewis",
            "Dan Aykroyd",
            "Dan Fogler",
            "Dan Stevens",
            "Dana White",
            "Daniel Craig",
            "Daniel Dae Kim",
            "Danielle Panabaker",
            "Danny DeVito",
            "Darth Vader",
            "Dave Bautista",
            "Dave Chappelle",
            "David Attenborough",
            "David Bowie",
            "David Goggins",
            "David Letterman",
            "David Oyelowo",
            "David Schwimmer",
            "David Tennant",
            "Deadpool",
            "Denis Leary",
            "Denzel Washington",
            "Derek Mears",
            "Diane Keaton",
            "Diane Kruger",
            "Dick Van Dyke",
            "Diego Luna",
            "Doja Cat",
            "Dolly Parton",
            "Domhnall Gleeson",
            "Dominic Cooper",
            "Donald Duck",
            "Donald Glover",
            "Donald Sutherland",
            "Donald Trump",
            "Donkey (Shrek)",
            "Donnie Yen",
            "Doutzen Kroes",
            "Dove Cameron",
            "Dr. Dre",
            "Dr. Phil",
            "Drake",
            "Drake Bell",
            "Dream (Minecraft)",
            "Drew Carey",
            "Dua Lipa",
            "Dwayne 'The Rock' Johnson",
            "Dwight Schrute",
            "Eartha Kitt",
            "Ed Sheeran",
            "Eddie Izzard",
            "Eddie Murphy",
            "Edward Asner",
            "Edward Elric",
            "Eli Roth",
            "Elisabeth Moss",
            "Elle Fanning",
            "Ellen Burstyn",
            "Ellen DeGeneres",
            "Elmo",
            "Elon Musk",
            "Elsa (Frozen)",
            "Elvis Presley",
            "Emile Hirsch",
            "Eminem",
            "Emma Watson",
            "Eren Jaeger",
            "Eric Cartman",
            "Ernie Hudson",
            "Ezra Miller",
            "Felicity Jones",
            "Fergie",
            "Fiona Shaw",
            "Florence Henderson",
            "Florence Pugh",
            "Floyd Mayweather",
            "Forest Whitaker",
            "Francia Raisa",
            "Frank Sinatra",
            "Freddie Highmore",
            "Freddie Mercury",
            "Freida Pinto",
            "GLaDOS",
            "Gabriel Iglesias",
            "Gal Gadot",
            "Gandalf",
            "Geena Davis",
            "Gemma Arterton",
            "Geralt of Rivia",
            "Geri Halliwell",
            "Giannis Antetokounmpo",
            "Gilbert Gottfried",
            "Gillian Jacobs",
            "Gina Carano",
            "Ginnifer Goodwin",
            "Glen Powell",
            "Glenn Close",
            "Gloria Steinem",
            "Goku",
            "Gollum Smeagol",
            "Gordon Lightfoot",
            "Gordon Ramsay",
            "Greta Gerwig",
            "Gugu Mbatha-Raw",
            "Guy Fieri",
            "Guy Pearce",
            "Gwendoline Christie",
            "Hailee Steinfeld",
            "Hans Zimmer",
            "Harrison Ford",
            "Harry Connick Jr.",
            "Harvey Keitel",
            "Hasan Minhaj",
            "Helena Bonham Carter",
            "Henry Cavill",
            "Hilary Swank",
            "Homer Simpson",
            "Howard Stern",
            "Howie Mandel",
            "Hugh Bonneville",
            "Hugh Jackman",
            "Hugh Laurie",
            "Hulk Hogan",
            "IShowSpeed",
            "Ian McKellen",
            "Ice Cube",
            "Ice Spice",
            "Idina Menzel",
            "Idris Elba",
            "Imelda Staunton",
            "Ingrid Bergman",
            "Irrfan Khan",
            "Isla Fisher",
            "Iwan Rheon",
            "J. K. Simmons",
            "J.J. Abrams",
            "Jack Black",
            "Jack Harlow",
            "Jack Lemmon",
            "Jacksepticeye",
            "Jacob Elordi",
            "Jake Paul",
            "James Corden",
            "James Earl Jones",
            "James May",
            "Janet Jackson",
            "Jared Leto",
            "Jason Bateman",
            "Jason Momoa",
            "Jason Segel",
            "Jason Statham",
            "Jay-Z",
            "Jeff Bezos",
            "Jeff Goldblum",
            "Jenna Ortega",
            "Jennifer Aniston",
            "Jennifer Carpenter",
            "Jennifer Coolidge",
            "Jensen Huang",
            "Jeremy Clarkson",
            "Jerry Seinfeld",
            "Jim Carrey",
            "Jimmy Fallon",
            "Joe Biden",
            "Joe Pesci",
            "Joe Rogan",
            "Joe Scott",
            "John Cena",
            "John F. Kennedy",
            "John Mulaney",
            "John Oliver",
            "Johnny Depp",
            "Johnny Galecki",
            "Jon Favreau",
            "Jordan Peterson",
            "Joseph Gordon-Levitt",
            "Josh Brolin",
            "Josh Gad",
            "Josh Groban",
            "Julia Louis-Dreyfus",
            "Julia Roberts",
            "Justin Bieber",
            "KSI",
            "Kai Cenat",
            "Kamala Harris",
            "Kanye West",
            "Katy Perry",
            "Keanu Reeves",
            "Keith David",
            "Kendrick Lamar",
            "Kermit the Frog",
            "Kesha",
            "Kevin Bacon",
            "Kevin Hart",
            "Kim Kardashian",
            "Kobe Bryant",
            "Kratos",
            "Kris Jenner",
            "Kristen Bell",
            "Kristen Stewart",
            "Kristen Wiig",
            "Lady Gaga",
            "LeBron James",
            "Leonardo DiCaprio",
            "Levi Ackerman",
            "Lex Fridman",
            "Liam Neeson",
            "Light Yagami",
            "Lil Wayne",
            "Linus (LTT)",
            "Lionel Messi",
            "Lizzo",
            "Logan Paul",
            "Lorde",
            "Lucille Ball",
            "Luffy (One Piece)",
            "Luigi",
            "Lupita Nyong'o",
            "Mahatma Gandhi",
            "Margot Robbie",
            "Marilyn Monroe",
            "Mario",
            "Mark Hamill",
            "Mark Wahlberg",
            "Mark Zuckerberg",
            "Markiplier",
            "Martha Stewart",
            "Martin Luther King Jr.",
            "Master Chief",
            "Matt Rife",
            "Matt Smith",
            "Matthew McConaughey",
            "Megan Thee Stallion",
            "Melissa McCarthy",
            "Meryl Streep",
            "Metro Boomin",
            "Michael B. Jordan",
            "Michael Jackson",
            "Michael Scott",
            "Mickey Mouse",
            "Mike Rowe",
            "Mike Tyson",
            "Miley Cyrus",
            "Morgan Freeman",
            "Morty Smith",
            "Mr. Krabs",
            "MrBeast",
            "Muhammad Ali",
            "Narendra Modi",
            "Naruto Uzumaki",
            "Natalie Portman",
            "Nate Diaz",
            "Neil deGrasse Tyson",
            "Nelson Mandela",
            "Nicki Minaj",
            "Nicolas Cage",
            "Nikki Glaser",
            "Ninja",
            "Notorious B.I.G.",
            "Oprah Winfrey",
            "Optimus Prime",
            "Oscar Isaac",
            "Owen Wilson",
            "Ozzy Osbourne",
            "Pat McAfee",
            "Patrick Star",
            "Patrick Stewart",
            "Patrick Warburton",
            "Paul Giamatti",
            "Pedro Pascal",
            "Penelope Cruz",
            "Peso Pluma",
            "Peter Griffin",
            "PewDiePie",
            "Picard",
            "Plankton",
            "Pokimane",
            "Post Malone",
            "Prince",
            "Princess Diana",
            "Queen Elizabeth II",
            "Quentin Tarantino",
            "Rachel Maddow",
            "Reese Witherspoon",
            "Richard Hammond",
            "Rick Sanchez",
            "Rihanna",
            "Robert De Niro",
            "Robert Downey Jr.",
            "Robin Williams",
            "Rooney Mara",
            "Ryan Reynolds",
            "Ryan Seacrest",
            "SZA",
            "Sabrina Carpenter",
            "Salma Hayek",
            "Sam Altman",
            "Samuel L. Jackson",
            "Sandra Bullock",
            "Scarlett Johansson",
            "Scooby-Doo",
            "Sean Connery",
            "Serena Williams",
            "Seth MacFarlane",
            "Seth Meyers",
            "Seth Rogen",
            "Shaggy Rogers",
            "Shakira",
            "Shannon Sharpe",
            "Shaquille O'Neal",
            "Shrek",
            "Snoop Dogg",
            "Sofia Vergara",
            "Sonic the Hedgehog",
            "SpiderMan (Tom Holland ver.)",
            "SpongeBob SquarePants",
            "Squidward Tentacles",
            "Stephen Colbert",
            "Stephen Curry",
            "Steve Carell",
            "Steve Harvey",
            "Steve Irwin",
            "Steve Jobs",
            "Stewie Griffin",
            "Stone Cold Steve Austin",
            "Sydney Sweeney",
            "Sylvester Stallone",
            "Tanjiro Kamado",
            "Taylor Swift",
            "Terminator",
            "Thanos",
            "The Joker (Animated)",
            "The Undertaker",
            "The Weeknd",
            "Tim Cook",
            "Timothee Chalamet",
            "Tom Brady",
            "Tom Cruise",
            "Tom Hanks",
            "Tom Hardy",
            "Tom Hiddleston",
            "Tommy Shelby",
            "Tony Stark",
            "Travis Scott",
            "Trevor Noah",
            "Tucker Carlson",
            "Tupac Shakur",
            "Tyler, The Creator",
            "Tyson Fury",
            "Usain Bolt",
            "Valkyrae",
            "Vegeta",
            "Vin Diesel",
            "Viola Davis",
            "Vladimir Putin",
            "Walter White",
            "Werner Herzog",
            "Whitney Houston",
            "Will Ferrell",
            "Will Smith",
            "Willem Dafoe",
            "Willie Nelson",
            "Winnie the Pooh",
            "Winston Churchill",
            "Woody (Toy Story)",
            "Yoda",
            "Zendaya",
            "Zoe Saldana",
            "xQc",
        ]
    ]
    """
    The voice to use for the speech. Available voices: Elon Musk, Mark Zuckerberg, Joe Rogan, Barack Obama, Morgan Freeman, Kanye West, Donald Trump, Joe Biden, Kim Kardashian, Taylor Swift, James Earl Jones, Samuel L. Jackson, Jeff Goldblum, David Attenborough, Sean Connery, Cillian Murphy, Anne Hathaway, Julia Roberts, Natalie Portman, Steve Carell, Amy Poehler, Stephen Colbert, Jimmy Fallon, David Letterman, Alex Trebek, Katy Perry, Prince, Kevin Bacon, Tom Hiddleston, Adam Driver, Alan Rickman, Alexz Johnson, Ana Gasteyer, Andrew Rannells, Arden Cho, Bear Grylls, Ben McKenzie, Ben Stiller, Ben Whishaw, Billie Joe Armstrong, Bingbing Li, Booboo Stewart, Bradley Steven Perry, Bruno Mars, Caity Lotz, Cameron Boyce, Candice Accola, Carrie Underwood, Casey Affleck, Caterina Scorsone, Cedric the Entertainer, Chace Crawford, Chadwick Boseman, Charlie Day, Chris Hemsworth, Chris Martin, Christopher Mintz-Plasse, Dan Fogler, Dan Stevens, Daniel Dae Kim, Danielle Panabaker, Dave Bautista, David Schwimmer, Denis Leary, Derek Mears, Diego Luna, Donald Glover, Donnie Yen, Doutzen Kroes, Dove Cameron, Dr. Dre, Drake Bell, Elle Fanning, Ernie Hudson, Fergie, Forest Whitaker, Francia Raisa, Freddie Highmore, Gillian Jacobs, Gina Carano, Ginnifer Goodwin, Gordon Ramsay, Guy Pearce, Gwendoline Christie, Hailee Steinfeld, Howie Mandel, Hugh Jackman, Hugh Laurie, J. K. Simmons, Jack Black, Jared Leto, Jennifer Carpenter, Kesha, Kris Jenner, Kristen Bell, Lorde, Matt Smith, Marilyn Monroe, Charlie Chaplin, Albert Einstein, Abraham Lincoln, John F. Kennedy, Lucille Ball, A.R. Rahman, Aamir Khan, Ajay Devgn, Akshay Kumar, Alain Delon, Alan Alda, Alan Cumming, Amitabh Bachchan, Ang Lee, Ansel Elgort, Anthony Anderson, Anthony Mackie, Armie Hammer, Asa Butterfield, B.J. Novak, Barbara Eden, Betty White, Bill Nighy, Bill Pullman, Blake Shelton, Bonnie Wright, Brad Paisley, Brendan Gleeson, Brian Cox, Bruno Ganz, Burt Reynolds, Carrie Fisher, Charles Dance, Chiwetel Ejiofor, Chris Pine, Christina Hendricks, Christina Ricci, Cyndi Lauper, Dakota Fanning, Damian Lewis, Dan Aykroyd, Daniel Craig, David Oyelowo, David Tennant, Diane Keaton, Diane Kruger, Dick Van Dyke, Domhnall Gleeson, Dominic Cooper, Donald Sutherland, Drew Carey, Eartha Kitt, Eddie Izzard, Edward Asner, Eli Roth, Elisabeth Moss, Ellen Burstyn, Emile Hirsch, Ezra Miller, Felicity Jones, Fiona Shaw, Florence Henderson, Freida Pinto, Geena Davis, Gemma Arterton, Geri Halliwell, Glenn Close, Gloria Steinem, Greta Gerwig, Gugu Mbatha-Raw, Hans Zimmer, Harry Connick Jr., Harvey Keitel, Helena Bonham Carter, Henry Cavill, Hilary Swank, Hugh Bonneville, Idina Menzel, Imelda Staunton, Ingrid Bergman, Irrfan Khan, Isla Fisher, Iwan Rheon, Jack Lemmon, Janet Jackson, Jason Bateman, Jason Segel, Jennifer Coolidge, Johnny Galecki, Jon Favreau, Joseph Gordon-Levitt, Josh Brolin, Josh Gad, Josh Groban, Julia Louis-Dreyfus, Kristen Stewart, Kristen Wiig, Rooney Mara, Caitriona Balfe, J.J. Abrams, Zoe Saldana, SpongeBob SquarePants, Patrick Star, Squidward Tentacles, Homer Simpson, Bart Simpson, Peter Griffin, Stewie Griffin, Eric Cartman, Rick Sanchez, Bugs Bunny, Mickey Mouse, Donald Duck, Shrek, Donkey (Shrek), Elsa (Frozen), Woody (Toy Story), Buzz Lightyear, Scooby-Doo, Shaggy Rogers, Bender (Futurama), Optimus Prime, Batman (Animated), The Joker (Animated), Darth Vader, Yoda, Gollum Smeagol, Gandalf, Winnie the Pooh, Kermit the Frog, Elmo, SpiderMan (Tom Holland ver.), Mario, Luigi, Sonic the Hedgehog, Naruto Uzumaki, Goku, Vegeta, Light Yagami, Luffy (One Piece), Edward Elric, Eren Jaeger, Levi Ackerman, Tanjiro Kamado, All Might, GLaDOS, Master Chief, Kratos, Arthur Morgan, Geralt of Rivia, Dwayne 'The Rock' Johnson, LeBron James, Shaquille O'Neal, Conor McGregor, Mike Tyson, Kobe Bryant, Floyd Mayweather, Cristiano Ronaldo, Lionel Messi, Serena Williams, Tom Brady, Stephen Curry, John Cena, Hulk Hogan, Stone Cold Steve Austin, The Undertaker, Nate Diaz, Charles Barkley, Shannon Sharpe, Drake, Rihanna, Eminem, Snoop Dogg, Jay-Z, Ed Sheeran, Billie Eilish, Ariana Grande, Adele, Post Malone, Travis Scott, Nicki Minaj, Cardi B, Doja Cat, Bad Bunny, Shakira, Justin Bieber, Sabrina Carpenter, Chappell Roan, Dua Lipa, The Weeknd, Miley Cyrus, Lady Gaga, Kendrick Lamar, Ozzy Osbourne, Freddie Mercury, Elvis Presley, Bob Marley, Frank Sinatra, MrBeast, PewDiePie, Kai Cenat, IShowSpeed, Markiplier, Jacksepticeye, KSI, Logan Paul, Jake Paul, Dream (Minecraft), Corpse Husband, xQc, Pokimane, Valkyrae, Ninja, Joe Scott, Linus (LTT), Ryan Reynolds, Tom Hanks, Robert Downey Jr., Will Smith, Denzel Washington, Leonardo DiCaprio, Brad Pitt, Keanu Reeves, Nicolas Cage, Al Pacino, Robert De Niro, Arnold Schwarzenegger, Sylvester Stallone, Vin Diesel, Jason Statham, Tom Cruise, Johnny Depp, Scarlett Johansson, Angelina Jolie, Jennifer Aniston, Emma Watson, Margot Robbie, Sydney Sweeney, Zendaya, Timothee Chalamet, Pedro Pascal, Oscar Isaac, Benedict Cumberbatch, Ian McKellen, Patrick Stewart, Christopher Walken, Matthew McConaughey, Harrison Ford, Mark Wahlberg, Owen Wilson, Seth Rogen, Kevin Hart, Adam Sandler, Jim Carrey, Eddie Murphy, Robin Williams, Will Ferrell, Melissa McCarthy, Awkwafina, Jason Momoa, Idris Elba, Tom Hardy, Michael B. Jordan, Austin Butler, Glen Powell, Paul Giamatti, Bryan Cranston, Bob Odenkirk, Vladimir Putin, Queen Elizabeth II, Winston Churchill, Martin Luther King Jr., Kamala Harris, Bernie Sanders, Alexandria Ocasio-Cortez, Narendra Modi, Oprah Winfrey, Ellen DeGeneres, Dr. Phil, Steve Harvey, Trevor Noah, John Oliver, James Corden, Ryan Seacrest, Howard Stern, Conan O'Brien, Seth Meyers, Bill Nye, Neil deGrasse Tyson, Guy Fieri, Dave Chappelle, Chris Rock, Jerry Seinfeld, Ali Wong, John Mulaney, Hasan Minhaj, Nikki Glaser, Matt Rife, Gabriel Iglesias, Bo Burnham, Jeff Bezos, Bill Gates, Steve Jobs, Tim Cook, Sam Altman, Jensen Huang, Gilbert Gottfried, James May, Jeremy Clarkson, Richard Hammond, Bob Ross, Anthony Bourdain, David Goggins, Jordan Peterson, Joe Pesci, Danny DeVito, Seth MacFarlane, Patrick Warburton, Keith David, Mark Hamill, Liam Neeson, Antonio Banderas, Sofia Vergara, Penelope Cruz, Gal Gadot, Cate Blanchett, Viola Davis, Meryl Streep, Sandra Bullock, Reese Witherspoon, Salma Hayek, Lupita Nyong'o, Florence Pugh, Jenna Ortega, Ana de Armas, Jacob Elordi, Barry White, Dolly Parton, Willie Nelson, Lil Wayne, 50 Cent, Ice Cube, Tupac Shakur, Notorious B.I.G., Bob Dylan, David Bowie, Michael Jackson, Whitney Houston, Amy Winehouse, SZA, Tyler, The Creator, Thanos, Tony Stark, Captain Jack Sparrow, Walter White, Tommy Shelby, Michael Scott, Dwight Schrute, Bowser, Usain Bolt, Tyson Fury, Dana White, Pat McAfee, Giannis Antetokounmpo, Lex Fridman, Ben Shapiro, Tucker Carlson, Martha Stewart, Gordon Lightfoot, Lizzo, Megan Thee Stallion, Ice Spice, 21 Savage, Metro Boomin, Jack Harlow, Peso Pluma, BTS Jungkook, Quentin Tarantino, Werner Herzog, Anderson Cooper, Rachel Maddow, Mahatma Gandhi, Muhammad Ali, Princess Diana, Nelson Mandela, Steve Irwin, Morty Smith, Andrew Huberman, Willem Dafoe, Mike Rowe, Terminator, Deadpool, Plankton, Mr. Krabs, Picard
    """


class _SerializerV1AiVoiceGeneratorCreateBodyStyle(pydantic.BaseModel):
    """
    Serializer for V1AiVoiceGeneratorCreateBodyStyle handling case conversions
    and file omissions as dictated by the API
    """

    model_config = pydantic.ConfigDict(
        populate_by_name=True,
    )

    prompt: str = pydantic.Field(
        alias="prompt",
    )
    voice_name: typing_extensions.Literal[
        "21 Savage",
        "50 Cent",
        "A.R. Rahman",
        "Aamir Khan",
        "Abraham Lincoln",
        "Adam Driver",
        "Adam Sandler",
        "Adele",
        "Ajay Devgn",
        "Akshay Kumar",
        "Al Pacino",
        "Alain Delon",
        "Alan Alda",
        "Alan Cumming",
        "Alan Rickman",
        "Albert Einstein",
        "Alex Trebek",
        "Alexandria Ocasio-Cortez",
        "Alexz Johnson",
        "Ali Wong",
        "All Might",
        "Amitabh Bachchan",
        "Amy Poehler",
        "Amy Winehouse",
        "Ana Gasteyer",
        "Ana de Armas",
        "Anderson Cooper",
        "Andrew Huberman",
        "Andrew Rannells",
        "Ang Lee",
        "Angelina Jolie",
        "Anne Hathaway",
        "Ansel Elgort",
        "Anthony Anderson",
        "Anthony Bourdain",
        "Anthony Mackie",
        "Antonio Banderas",
        "Arden Cho",
        "Ariana Grande",
        "Armie Hammer",
        "Arnold Schwarzenegger",
        "Arthur Morgan",
        "Asa Butterfield",
        "Austin Butler",
        "Awkwafina",
        "B.J. Novak",
        "BTS Jungkook",
        "Bad Bunny",
        "Barack Obama",
        "Barbara Eden",
        "Barry White",
        "Bart Simpson",
        "Batman (Animated)",
        "Bear Grylls",
        "Ben McKenzie",
        "Ben Shapiro",
        "Ben Stiller",
        "Ben Whishaw",
        "Bender (Futurama)",
        "Benedict Cumberbatch",
        "Bernie Sanders",
        "Betty White",
        "Bill Gates",
        "Bill Nighy",
        "Bill Nye",
        "Bill Pullman",
        "Billie Eilish",
        "Billie Joe Armstrong",
        "Bingbing Li",
        "Blake Shelton",
        "Bo Burnham",
        "Bob Dylan",
        "Bob Marley",
        "Bob Odenkirk",
        "Bob Ross",
        "Bonnie Wright",
        "Booboo Stewart",
        "Bowser",
        "Brad Paisley",
        "Brad Pitt",
        "Bradley Steven Perry",
        "Brendan Gleeson",
        "Brian Cox",
        "Bruno Ganz",
        "Bruno Mars",
        "Bryan Cranston",
        "Bugs Bunny",
        "Burt Reynolds",
        "Buzz Lightyear",
        "Caitriona Balfe",
        "Caity Lotz",
        "Cameron Boyce",
        "Candice Accola",
        "Captain Jack Sparrow",
        "Cardi B",
        "Carrie Fisher",
        "Carrie Underwood",
        "Casey Affleck",
        "Cate Blanchett",
        "Caterina Scorsone",
        "Cedric the Entertainer",
        "Chace Crawford",
        "Chadwick Boseman",
        "Chappell Roan",
        "Charles Barkley",
        "Charles Dance",
        "Charlie Chaplin",
        "Charlie Day",
        "Chiwetel Ejiofor",
        "Chris Hemsworth",
        "Chris Martin",
        "Chris Pine",
        "Chris Rock",
        "Christina Hendricks",
        "Christina Ricci",
        "Christopher Mintz-Plasse",
        "Christopher Walken",
        "Cillian Murphy",
        "Conan O'Brien",
        "Conor McGregor",
        "Corpse Husband",
        "Cristiano Ronaldo",
        "Cyndi Lauper",
        "Dakota Fanning",
        "Damian Lewis",
        "Dan Aykroyd",
        "Dan Fogler",
        "Dan Stevens",
        "Dana White",
        "Daniel Craig",
        "Daniel Dae Kim",
        "Danielle Panabaker",
        "Danny DeVito",
        "Darth Vader",
        "Dave Bautista",
        "Dave Chappelle",
        "David Attenborough",
        "David Bowie",
        "David Goggins",
        "David Letterman",
        "David Oyelowo",
        "David Schwimmer",
        "David Tennant",
        "Deadpool",
        "Denis Leary",
        "Denzel Washington",
        "Derek Mears",
        "Diane Keaton",
        "Diane Kruger",
        "Dick Van Dyke",
        "Diego Luna",
        "Doja Cat",
        "Dolly Parton",
        "Domhnall Gleeson",
        "Dominic Cooper",
        "Donald Duck",
        "Donald Glover",
        "Donald Sutherland",
        "Donald Trump",
        "Donkey (Shrek)",
        "Donnie Yen",
        "Doutzen Kroes",
        "Dove Cameron",
        "Dr. Dre",
        "Dr. Phil",
        "Drake",
        "Drake Bell",
        "Dream (Minecraft)",
        "Drew Carey",
        "Dua Lipa",
        "Dwayne 'The Rock' Johnson",
        "Dwight Schrute",
        "Eartha Kitt",
        "Ed Sheeran",
        "Eddie Izzard",
        "Eddie Murphy",
        "Edward Asner",
        "Edward Elric",
        "Eli Roth",
        "Elisabeth Moss",
        "Elle Fanning",
        "Ellen Burstyn",
        "Ellen DeGeneres",
        "Elmo",
        "Elon Musk",
        "Elsa (Frozen)",
        "Elvis Presley",
        "Emile Hirsch",
        "Eminem",
        "Emma Watson",
        "Eren Jaeger",
        "Eric Cartman",
        "Ernie Hudson",
        "Ezra Miller",
        "Felicity Jones",
        "Fergie",
        "Fiona Shaw",
        "Florence Henderson",
        "Florence Pugh",
        "Floyd Mayweather",
        "Forest Whitaker",
        "Francia Raisa",
        "Frank Sinatra",
        "Freddie Highmore",
        "Freddie Mercury",
        "Freida Pinto",
        "GLaDOS",
        "Gabriel Iglesias",
        "Gal Gadot",
        "Gandalf",
        "Geena Davis",
        "Gemma Arterton",
        "Geralt of Rivia",
        "Geri Halliwell",
        "Giannis Antetokounmpo",
        "Gilbert Gottfried",
        "Gillian Jacobs",
        "Gina Carano",
        "Ginnifer Goodwin",
        "Glen Powell",
        "Glenn Close",
        "Gloria Steinem",
        "Goku",
        "Gollum Smeagol",
        "Gordon Lightfoot",
        "Gordon Ramsay",
        "Greta Gerwig",
        "Gugu Mbatha-Raw",
        "Guy Fieri",
        "Guy Pearce",
        "Gwendoline Christie",
        "Hailee Steinfeld",
        "Hans Zimmer",
        "Harrison Ford",
        "Harry Connick Jr.",
        "Harvey Keitel",
        "Hasan Minhaj",
        "Helena Bonham Carter",
        "Henry Cavill",
        "Hilary Swank",
        "Homer Simpson",
        "Howard Stern",
        "Howie Mandel",
        "Hugh Bonneville",
        "Hugh Jackman",
        "Hugh Laurie",
        "Hulk Hogan",
        "IShowSpeed",
        "Ian McKellen",
        "Ice Cube",
        "Ice Spice",
        "Idina Menzel",
        "Idris Elba",
        "Imelda Staunton",
        "Ingrid Bergman",
        "Irrfan Khan",
        "Isla Fisher",
        "Iwan Rheon",
        "J. K. Simmons",
        "J.J. Abrams",
        "Jack Black",
        "Jack Harlow",
        "Jack Lemmon",
        "Jacksepticeye",
        "Jacob Elordi",
        "Jake Paul",
        "James Corden",
        "James Earl Jones",
        "James May",
        "Janet Jackson",
        "Jared Leto",
        "Jason Bateman",
        "Jason Momoa",
        "Jason Segel",
        "Jason Statham",
        "Jay-Z",
        "Jeff Bezos",
        "Jeff Goldblum",
        "Jenna Ortega",
        "Jennifer Aniston",
        "Jennifer Carpenter",
        "Jennifer Coolidge",
        "Jensen Huang",
        "Jeremy Clarkson",
        "Jerry Seinfeld",
        "Jim Carrey",
        "Jimmy Fallon",
        "Joe Biden",
        "Joe Pesci",
        "Joe Rogan",
        "Joe Scott",
        "John Cena",
        "John F. Kennedy",
        "John Mulaney",
        "John Oliver",
        "Johnny Depp",
        "Johnny Galecki",
        "Jon Favreau",
        "Jordan Peterson",
        "Joseph Gordon-Levitt",
        "Josh Brolin",
        "Josh Gad",
        "Josh Groban",
        "Julia Louis-Dreyfus",
        "Julia Roberts",
        "Justin Bieber",
        "KSI",
        "Kai Cenat",
        "Kamala Harris",
        "Kanye West",
        "Katy Perry",
        "Keanu Reeves",
        "Keith David",
        "Kendrick Lamar",
        "Kermit the Frog",
        "Kesha",
        "Kevin Bacon",
        "Kevin Hart",
        "Kim Kardashian",
        "Kobe Bryant",
        "Kratos",
        "Kris Jenner",
        "Kristen Bell",
        "Kristen Stewart",
        "Kristen Wiig",
        "Lady Gaga",
        "LeBron James",
        "Leonardo DiCaprio",
        "Levi Ackerman",
        "Lex Fridman",
        "Liam Neeson",
        "Light Yagami",
        "Lil Wayne",
        "Linus (LTT)",
        "Lionel Messi",
        "Lizzo",
        "Logan Paul",
        "Lorde",
        "Lucille Ball",
        "Luffy (One Piece)",
        "Luigi",
        "Lupita Nyong'o",
        "Mahatma Gandhi",
        "Margot Robbie",
        "Marilyn Monroe",
        "Mario",
        "Mark Hamill",
        "Mark Wahlberg",
        "Mark Zuckerberg",
        "Markiplier",
        "Martha Stewart",
        "Martin Luther King Jr.",
        "Master Chief",
        "Matt Rife",
        "Matt Smith",
        "Matthew McConaughey",
        "Megan Thee Stallion",
        "Melissa McCarthy",
        "Meryl Streep",
        "Metro Boomin",
        "Michael B. Jordan",
        "Michael Jackson",
        "Michael Scott",
        "Mickey Mouse",
        "Mike Rowe",
        "Mike Tyson",
        "Miley Cyrus",
        "Morgan Freeman",
        "Morty Smith",
        "Mr. Krabs",
        "MrBeast",
        "Muhammad Ali",
        "Narendra Modi",
        "Naruto Uzumaki",
        "Natalie Portman",
        "Nate Diaz",
        "Neil deGrasse Tyson",
        "Nelson Mandela",
        "Nicki Minaj",
        "Nicolas Cage",
        "Nikki Glaser",
        "Ninja",
        "Notorious B.I.G.",
        "Oprah Winfrey",
        "Optimus Prime",
        "Oscar Isaac",
        "Owen Wilson",
        "Ozzy Osbourne",
        "Pat McAfee",
        "Patrick Star",
        "Patrick Stewart",
        "Patrick Warburton",
        "Paul Giamatti",
        "Pedro Pascal",
        "Penelope Cruz",
        "Peso Pluma",
        "Peter Griffin",
        "PewDiePie",
        "Picard",
        "Plankton",
        "Pokimane",
        "Post Malone",
        "Prince",
        "Princess Diana",
        "Queen Elizabeth II",
        "Quentin Tarantino",
        "Rachel Maddow",
        "Reese Witherspoon",
        "Richard Hammond",
        "Rick Sanchez",
        "Rihanna",
        "Robert De Niro",
        "Robert Downey Jr.",
        "Robin Williams",
        "Rooney Mara",
        "Ryan Reynolds",
        "Ryan Seacrest",
        "SZA",
        "Sabrina Carpenter",
        "Salma Hayek",
        "Sam Altman",
        "Samuel L. Jackson",
        "Sandra Bullock",
        "Scarlett Johansson",
        "Scooby-Doo",
        "Sean Connery",
        "Serena Williams",
        "Seth MacFarlane",
        "Seth Meyers",
        "Seth Rogen",
        "Shaggy Rogers",
        "Shakira",
        "Shannon Sharpe",
        "Shaquille O'Neal",
        "Shrek",
        "Snoop Dogg",
        "Sofia Vergara",
        "Sonic the Hedgehog",
        "SpiderMan (Tom Holland ver.)",
        "SpongeBob SquarePants",
        "Squidward Tentacles",
        "Stephen Colbert",
        "Stephen Curry",
        "Steve Carell",
        "Steve Harvey",
        "Steve Irwin",
        "Steve Jobs",
        "Stewie Griffin",
        "Stone Cold Steve Austin",
        "Sydney Sweeney",
        "Sylvester Stallone",
        "Tanjiro Kamado",
        "Taylor Swift",
        "Terminator",
        "Thanos",
        "The Joker (Animated)",
        "The Undertaker",
        "The Weeknd",
        "Tim Cook",
        "Timothee Chalamet",
        "Tom Brady",
        "Tom Cruise",
        "Tom Hanks",
        "Tom Hardy",
        "Tom Hiddleston",
        "Tommy Shelby",
        "Tony Stark",
        "Travis Scott",
        "Trevor Noah",
        "Tucker Carlson",
        "Tupac Shakur",
        "Tyler, The Creator",
        "Tyson Fury",
        "Usain Bolt",
        "Valkyrae",
        "Vegeta",
        "Vin Diesel",
        "Viola Davis",
        "Vladimir Putin",
        "Walter White",
        "Werner Herzog",
        "Whitney Houston",
        "Will Ferrell",
        "Will Smith",
        "Willem Dafoe",
        "Willie Nelson",
        "Winnie the Pooh",
        "Winston Churchill",
        "Woody (Toy Story)",
        "Yoda",
        "Zendaya",
        "Zoe Saldana",
        "xQc",
    ] = pydantic.Field(
        alias="voice_name",
    )
